export const OrgnizationList = [
    "Andhra Pradesh Orgnization",
    "Arunachal Pradesh Orgnization",
    "Assam Orgnization",
    "Bihar Orgnization",
    "Chhattisgarh Orgnization",
    "Goa Orgnization",
    "Gujarat Orgnization",
    "Haryana Orgnization",
    "Himachal Pradesh Orgnization",
    "Jammu and Kashmir Orgnization",
    "Jharkhand Orgnization",
    "Karnataka Orgnization",
    "Kerala Orgnization",
    "Madhya Pradesh Orgnization",
    "Maharashtra Orgnization",
    "Manipur Orgnization",
]